### ISSUE TITLE
Imported .kit file variables not working

### ISSUE THREAD

**Issue by benjaminsinger** [Lukx/gulp-kit#2] opened 2014-11-24 21:44 UTC
Hi, I'm getting compilation errors importing a header.kit file with placeholder variables when defining variables as below in my index.kit template file.

``` html
<!-- $pageTitle = home -->
<!-- $pageDescription = home  -->
<!-- $bodyClass = home -->
<!-- @include "header.kit" -->
```

If i don't declare the variables to be empty in the initial header.kit partial file, I get the following error code in terminal:

``` bash
Error: Line 9 of header.kit: The variable $pageTitle is undefined.
    at Kit._compileToken (/Users/Ben/Sites/F5Gulp/node_modules/gulp-kit/node_modules/node-kit/lib/node-kit.js:315:19)
    at Kit.compile (/Users/Ben/Sites/F5Gulp/node_modules/gulp-kit/node_modules/node-kit/lib/node-kit.js:116:14)
    at Kit.toString (/Users/Ben/Sites/F5Gulp/node_modules/gulp-kit/node_modules/node-kit/lib/node-kit.js:128:28)
    at kit (/Users/Ben/Sites/F5Gulp/node_modules/gulp-kit/node_modules/node-kit/lib/node-kit.js:21:25)
    at DestroyableTransform.transform [as _transform] (/Users/Ben/Sites/F5Gulp/node_modules/gulp-kit/index.js:26:18)
    at DestroyableTransform.Transform._read (/Users/Ben/Sites/F5Gulp/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/Ben/Sites/F5Gulp/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/Ben/Sites/F5Gulp/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/Users/Ben/Sites/F5Gulp/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/Users/Ben/Sites/F5Gulp/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
```

**Comment by joshuatuscan** [comment] 2015-01-08 02:05
The same thing is happening for me. I'm declaring the variable in the master file, then importing a partial and trying to access the variable in the import, and the same error spits out.

**Comment by Christo44** [comment] 2015-06-23 15:01
Yep same here.  At first I thought it was something else converting from codekit to gulp-kit with node-kit but it's not reading the variables declared in the root file in the import.

**Comment by Christo44** [comment] 2015-06-23 15:35
Something to wonder, declaring 1 single variable does work.

**Comment by lukx** [comment] 2015-09-11 04:36
Hey, 
I had reported a very similar issue back in this pull request for node-kit, 
 https://github.com/jeremyworboys/node-kit/issues/9

Maybe either of you is able to reproduce whether it had to do with that bug in node kit? I personally still don't have a real code kit installation available, thus I can not proceed with the other PR. Still, I believe this library alone is too stupid to bring the bug in, so it must be inside node-kit

**Comment by benjaminsinger** [comment] 2015-09-18 11:47
I'm afraid I'm a tad out of my depth with straight node and I have Codekit, so it's not a huge issue. I'd just like to be able to move the whole show over to Gulp, but if the problem is with node-kit then I guess it's NBD. Thanks for taking time to put this together, anyway.

**Comment by fatso83** [comment] 2015-09-28 16:23
I am looking into it. 

@benjaminsinger : I am quite confident you could pull it off if you tried :-)

```
var kit = require('node-kit');
var html = kit('path/to/file.kit');
console.log(html);
```

**Comment by fatso83** [comment] 2015-09-28 17:27
@benjaminsinger This problem was fixed in node-kit last November. I just verified that this bug no longer exists. My guess is that you haven't updated your installation since then.

Try this as a fix:

```
rm -r node_modules
npm install

#force the latest version in case you specified an older in your package.json
npm install Lukx/gulp-kit 

# run your gulp stuff
gulp
```

**Comment by fdeneux** [comment] 2015-09-28 18:42
@fatso83 Having the same issue running a fresh install of gulp-kit (with node-kit v0.8.1).

Issue: kit variables that are defined in index.kit and used in a partial (included after the variables) are undefined. The setup works fine in CodeKit itself.

index.kit:

``` html
<!-- $title = Boilerplate -->
<!-- $description = Description -->
<!-- @include "includes/header" -->
```

_header.kit:

```
<!doctype html>
<html class="no-js" lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title><!-- $title --> | Project</title>
    <meta name="description" content="<!-- $description -->">
    <link rel="author" href="humans.txt" />
```

Error:

```
Error: Line 8 of _header.kit: The variable $title is undefined.
    at Kit._compileToken (/Users/fabiandeneux/Dropbox/Repositories/GitLab/t-gulp-complete/node_modules/gulp-kit/node_modules/node-kit/lib/node-kit.js:315:19)
    at Kit.compile (/Users/fabiandeneux/Dropbox/Repositories/GitLab/t-gulp-complete/node_modules/gulp-kit/node_modules/node-kit/lib/node-kit.js:116:14)
    at Kit.toString (/Users/fabiandeneux/Dropbox/Repositories/GitLab/t-gulp-complete/node_modules/gulp-kit/node_modules/node-kit/lib/node-kit.js:128:28)
    at kit (/Users/fabiandeneux/Dropbox/Repositories/GitLab/t-gulp-complete/node_modules/gulp-kit/node_modules/node-kit/lib/node-kit.js:21:25)
    at DestroyableTransform.transform [as _transform] (/Users/fabiandeneux/Dropbox/Repositories/GitLab/t-gulp-complete/node_modules/gulp-kit/index.js:26:18)
    at DestroyableTransform.Transform._read (/Users/fabiandeneux/Dropbox/Repositories/GitLab/t-gulp-complete/node_modules/gulp-kit/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/fabiandeneux/Dropbox/Repositories/GitLab/t-gulp-complete/node_modules/gulp-kit/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/fabiandeneux/Dropbox/Repositories/GitLab/t-gulp-complete/node_modules/gulp-kit/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/Users/fabiandeneux/Dropbox/Repositories/GitLab/t-gulp-complete/node_modules/gulp-kit/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/Users/fabiandeneux/Dropbox/Repositories/GitLab/t-gulp-complete/node_modules/gulp-kit/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
```

**Comment by fatso83** [comment] 2015-09-28 19:30
@fdeneux I am quite tempted to say that you must be doing _something_ wrong or that something _is_ wrong in your setup. See https://github.com/fatso83/node-kit/commit/2722c7ec75821fbd5ac8f225d5f42449f1cd1065

That commit includes your exact input files. My test is simply
1. Install the dependencies
2. Go the the dir containing your kit file
3. Run gulp
4. See that no errors were produced.

Clone my repo, checkout the commit, and try for yourself. This is not a bug, unless you can supply a reproducible test case.

Have you tried clearing your cache first? 
`npm cache clean && rm -r node_modules`

**Comment by fatso83** [comment] 2015-09-28 19:35
Hey, I think I know what is probably going on:

```
 "dependencies": {
    "node-kit": "git://github.com/Lukx/node-kit.git#647e3e28c02a3ea7b8d83913255e37e81575764b",
    "through2": "~0.6.1",
    "gulp-util": "~3.0.1"
  },
```

That is the dependency section from the published gulp-kit version. It is explicitly using an old version of node-kit.

The version of gulp-kit on NPM is from September, while the node-kit version that fixes the problem is from Novemer ... 

```
   '0.1.1': '2014-09-18T12:02:47.099Z'
```

**Comment by fdeneux** [comment] 2015-09-28 19:52
@fatso83 It makes sense, thank you for your time.

**Comment by fatso83** [comment] 2015-09-28 20:03
@fdeneux At least it was not a user error :-)

The thing I don't understand is actually why it does not fail for me using the published version ... 

```
 grep 'version\"' node_modules/gulp-kit/node_modules/node-kit/package.json
# =>  "version": "0.6.0",
```

This version is not supposed to work, AFAIK, with this problem. So there is something going on I don't understand.

**Comment by fatso83** [comment] 2015-09-28 20:05
The other thing I seem to not understand is where you got the version that includes node-kit@0.8.1? Did you install the GitHub version? Like `npm install Lukx/gulp-kit`?

**Comment by fdeneux** [comment] 2015-09-28 20:07
@fatso83 Yes I used the fix you suggested to @benjaminsinger.

**Comment by fdeneux** [comment] 2015-09-28 20:27
@fatso83 I just found the cause of the error.

Notice the source in each of the tasks. The first one fires the variable undefined error as it searches for all kit files, including the partials. The second one gives no error as it compiles only kit files that aren't in a subdir. Still... shouldn't partials be considered partials by the compiler, by being ignored or have their variables looked up in the main .kit file? All files compile just fine, even with the error which seems weird.

``` javascript
module.exports = function (gulp, plugins, config) {
  return function () {
    gulp.src(config.paths.app.kit + '**/*')
      .pipe(plugins.kit())
      .pipe(gulp.dest(config.paths.public.html))
      .pipe(plugins.notify({
        message: 'Kit files compiled, ' + config.settings.name + '!',
        onLast: true
      }))
  };
};
```

``` javascript
module.exports = function (gulp, plugins, config) {
  return function () {
    gulp.src(config.paths.app.kit + '*.kit')
      .pipe(plugins.kit())
      .pipe(gulp.dest(config.paths.public.html))
      .pipe(plugins.notify({
        message: 'Kit files compiled, ' + config.settings.name + '!',
        onLast: true
      }))
  };
};
```

**Comment by fatso83** [comment] 2015-09-28 20:41
Good catch! As I wrote grunt-codekit, you can see that the case of partials is handled in the plugin there. @Lukx could add something like [this](https://github.com/fatso83/grunt-codekit/blob/master/tasks/codekit.js#L74-L77) to filter out partials.

It's not really that weird that all the files compile, as long as the node process does not crash. That means all the "correct" ones are compiled, and the rest is just simply doing nothing.

**Comment by fdeneux** [comment] 2015-09-28 20:47
@Lukx adding such a filter would be highly appreciated.
Once again, thank you for your time @fatso83.

**Comment by lukx** [comment] 2015-10-01 08:41
Thank you so much for all of your engagement. I have ceased to use kit a year ago and therefore was not able to invest time professionally anymore, so I apologize for leaving you in the unclear so long.
I have pushed version 0.2.0 to NPM and will now try to look out for a new maintainer of the package.

**Comment by ScottSmith95** [comment] 2015-10-01 20:42
Seems like @fatso83 would be a good maintainer, if he's interested. ;)

**Comment by fatso83** [comment] 2015-10-01 21:34
@Lukx, like yourself, I haven't actually used Kit in a while, but I wouldn't mind maintaining this, as I suspect it has relatively few issues.  if you can figure out how to transfer ownership of the NPM package I could take the role of maintainer.

**Comment by fatso83** [comment] 2016-10-04 12:03
OK, I got the maintainer bits now, so I can try to fix any remaining issues. Will look into this now.

**Comment by fatso83** [comment] 2016-10-04 12:04
Damn, I forgot I fixed this a looong time ago (80cd048eee81eeea31e92de446905065d885c93b). Closing.

**Closed as completed by fatso83** 2016-10-04 12:04 UTC

**Comment by jacquesletesson** [comment] 2016-12-12 12:11
This issue seems to remain with a fresh gulp-kit install.

```
<!-- $title = This is my title 2 -->
<!-- @import partials/_header.kit -->
```

```
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title><!-- $title? --></title>
</head>

```

> Error: Line 7 of _header.kit: The variable $title is undefined.

**Comment by fatso83** [comment] 2016-12-12 19:33
Hmm ... just so that different issues aren't mixed up, does this work when you remove the question mark from the variable name? Might just be the syntax.

**Comment by dongepulango** [comment] 2018-01-03 14:37
Any fix on this?

**Comment by NutsNGum** [comment] 2018-01-03 15:17
I'm not sure if it's worth fixing at this point @dongepulango. Unless you are tied into the platform, there are substantially better options for building statics. Nunjucks and Mustache to name just two, both have a wealth of documentation and support available.

**Comment by dongepulango** [comment] 2018-01-03 19:33
@NutsNGum Thanks for the suggestion, I will have a look on those two.

**Comment by fatso83** [comment] 2018-01-04 09:42
As can be seen from the linked issue, this is a feature that needs to be added to node-kit. See [Kit Optionals](https://github.com/jeremyworboys/node-kit/issues/19). From earlier, I know the source code of node-kit to be very nice to work with, so if you need this to be working @dongepulango, you can probably add it in an hour or two!

Other than that, this discussion about support for optional variables has nothing to do with this issue. If node-kit will support this in the future, it will be automatically supported in this lib as well. Please continue any discussion in the node-kit issue tracker.
